# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule/schedule.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("schedule/schedule.proto", :syntax => :proto3) do
    add_message "schedule.ListScheduleRequest" do
      optional :name, :string, 1
    end
    add_message "schedule.CreateGrpcScheduleRequest" do
      optional :schedule, :message, 2, "schedule.Schedule"
      optional :grpcCall, :message, 3, "schedule.GrpcCall"
    end
    add_message "schedule.UpdateGrpcScheduleRequest" do
      optional :schedule, :message, 2, "schedule.Schedule"
      optional :grpcCall, :message, 3, "schedule.GrpcCall"
    end
    add_message "schedule.CreateBrokerScheduleRequest" do
      optional :schedule, :message, 2, "schedule.Schedule"
      optional :brokerEvent, :message, 3, "schedule.BrokerEvent"
    end
    add_message "schedule.UpdateBrokerScheduleRequest" do
      optional :schedule, :message, 2, "schedule.Schedule"
      optional :brokerEvent, :message, 3, "schedule.BrokerEvent"
    end
    add_message "schedule.Schedule" do
      optional :message, :string, 1
    end
    add_message "schedule.GrpcCall" do
      optional :ClientName, :string, 1
      optional :MethodName, :string, 2
      optional :PayloadStr, :string, 3
    end
    add_message "schedule.BrokerEvent" do
      optional :Topic, :string, 1
      optional :Key, :string, 2
      optional :Message, :string, 3
    end
  end
end

module Schedule
  ListScheduleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("schedule.ListScheduleRequest").msgclass
  CreateGrpcScheduleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("schedule.CreateGrpcScheduleRequest").msgclass
  UpdateGrpcScheduleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("schedule.UpdateGrpcScheduleRequest").msgclass
  CreateBrokerScheduleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("schedule.CreateBrokerScheduleRequest").msgclass
  UpdateBrokerScheduleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("schedule.UpdateBrokerScheduleRequest").msgclass
  Schedule = Google::Protobuf::DescriptorPool.generated_pool.lookup("schedule.Schedule").msgclass
  GrpcCall = Google::Protobuf::DescriptorPool.generated_pool.lookup("schedule.GrpcCall").msgclass
  BrokerEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("schedule.BrokerEvent").msgclass
end
